# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Download Launch4j
        run: |
          curl https://jaist.dl.sourceforge.net/project/launch4j/launch4j-3/3.50/launch4j-3.50-linux-x64.tgz -o launch4j.tgz
          tar -xzvf launch4j.tgz
          
      - name: Run Launch4j
        run: |
          cd assets/launch4j
          java -jar $GITHUB_WORKSPACE/launch4j/launch4j.jar launch4j.xml
      - name: Upload Artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build/libs/